### PR TITLE
remove go-mode-autoloads because it will be generated during installa…

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://github.com/melpa/melpa/issues/5019

### CODE REVIEW

**Comment by dominikh** [comment]
The file exists because of historical reasons (the original go-mode that we replaced included the file, unfortunately.)

But at this point, the presence of the file is probably causing more harm than good.

**Comment by gnufied** [comment]
This PR will not be enough to fix the bug though. I think we will need `;;;###autoload` comments in `go-mode.el` too.

**Comment by dominikh** [comment]
go-mode.el has plenty of autoload cookies, and to the best of my knowledge they cover all the functions that are worth autoloading. Did we miss any?

FTR, the existing go-mode-autoloads file is generated from the autoload cookies, it isn't hand-written.

**Comment by tarsius** [comment]
> FTR, the existing go-mode-autoloads file is generated from the autoload cookies, it isn't hand-written.

So you should be good to go. (Consider this a friendly ping.)

**Comment by dominikh** [comment]
@tarsius there we go.

**Comment by tarsius** [comment]
Thanks!

**Pull request closed without merging**
