### PR TITLE
Add godoc-mode.

### PR DESCRIPTION
**Pull request by buzztaiki**
To ease to customize godoc. ref. #87

### CODE REVIEW

**Comment by buzztaiki** [comment]
With godoc-mode, I can highligt godoc using following snippet:

```emacs-lisp
(defun godoc-highlight ()
  (let ((st (make-syntax-table go-mode-syntax-table)))
    (modify-syntax-entry ?\' "w" st)
    (set-syntax-table st))
  (set (make-local-variable 'font-lock-defaults) '(go--build-font-lock-keywords)))
(add-hook 'godoc-mode-hook 'godoc-highlight)
```

**Comment by dominikh** [comment]
Shouldn't we still enable the view-mode minor-mode by default? Otherwise, godoc-mode becomes a very stripped down version of what we have today.

**Comment by buzztaiki** [comment]
Should I `view-mode-enter` in godoc-mode?

**Comment by dominikh** [comment]
I think that's the best approach, yeah.

**Comment by buzztaiki** [comment]
I added.

**Comment by buzztaiki** [comment]
I was able to add `view-mode-enter` into `godoc-mode-hook`. But I have select simplest one.

**Comment by dominikh** [comment]
Merged as 64be4a31390a62d248da5c0509aaa0de09b8e4f4 - thank you.

**Comment by buzztaiki** [comment]
Thanks!

**Pull request closed without merging**
