### PR TITLE
adding go-alternate to go-mode.el

### PR DESCRIPTION
**Pull request by c25l**
Hey,
This is a useful convenience function for switching between files and their tests. If there is anything wrong stylistically here, I'd be happy to make changes.

Thanks!
Chris

### CODE REVIEW

**Comment by dominikh** [comment]
Thank you, but go-mode already supports this feature via `ff-find-other-file`. See the `go-other-file-alist` variable for details.

**Comment by c25l** [comment]
Yeah, i see the implementation now, and it really works. I cannot, however, find any documentation about it anywhere else in go-mode.el, nor is there a keybinding for it. Especially for the "I'm new to {E|Space}macs" crowd, it might be nice to have either/both. I would be willing to add this, if you think it's valid.

**Comment by c25l** [comment]
Also thanks for taking the time to look over my PR. I really like using go-mode.el.

**Comment by dominikh** [comment]
You can send a PR for the readme if you'd like, possibly in the list of standard Emacs features that we  support, we already list things such as beginning-of-defun.

On a broader scope, however. people should learn Emacs, not go-mode.

**Pull request closed without merging**
