### PR TITLE
Add `go-play-browse-function'.

### PR DESCRIPTION
**Pull request by ruediger**
This allows changing the behavior of `go-play-region` to, e.g., browse
the url.

Maybe `kill-new` should be moved to an option as well.

* go-mode.el (go-play-browse-function): New defcustom.
  (go-play-region): Call `go-play-browse-function` with URL.

### CODE REVIEW

**Comment by dominikh** [comment]
> Maybe kill-new should be moved to an option as well

I'm wondering if it should become another choice for `go-play-browse-function` or it's own setting alltogether.

**Comment by ruediger** [comment]
The problem when adding it to `go-play-browse-function` is that most users probably want it copied to the kill ring *and* a message.  This would require a new function like `go--kill-new-and-message`.

**Comment by dominikh** [comment]
The same can be said for most permutations of {message, kill, browse}, though, i.e. also message+browse.  How are other modes/functions handling this?

**Comment by ruediger** [comment]
I've updated the commit to add a `go--kill-new-message` function. That should take care of the most common cases in my opinion. I guess most users want either `browse-url` or `kill-new`+`message` (the old behavior and still default). If a user wants a more exotic or specific combination than she can simply create her own function or lambda and set it.

**Comment by dominikh** [comment]
Merged as 466e188, thanks.

**Pull request closed without merging**
