### PR TITLE
Add a new customization variable to allow adding additional flags to …

### PR DESCRIPTION
**Pull request by phst**
…gorename

### CODE REVIEW

**Comment by dominikh** [comment]
Which additional flags would you pass to gorename with this?

**Comment by phst** [comment]
There are a couple of generic flags such as `-v` that are currently not covered by other options.

**Comment by dominikh** [comment]
The flags that are not supported are `-from`, `-d`, and `-v`. Using either `-from` or `-d` would break the function, leaving just `-v`. It would make more sense to add an option specifically for verbose logging.

**Comment by dominikh** [comment]
Got no response, and gorename isn't all that useful anymore with gopls. Closing.

**Pull request closed without merging**
